"""Full backup builder — creates a .tar.gz archive with all databases,
uploads, encryption keys, meta.json, and RESTORE.md.

Used by /api/system/backup/full endpoint (streaming mode) and can also
be run standalone for manual backups.

Archive structure:
    databases/
        aspidus_crm.db
        aspidus_portal.db
        aspidus_audit.db
    keys/
        vault.key
        instance/secret.key
    uploads/           (all uploaded files)
    portal_uploads/    (all portal-uploaded files)
    meta.json          (row counts, SHA256, timestamps, version)
    RESTORE.md         (step-by-step restore instructions)
"""

import hashlib
import io
import json
import os
import sqlite3
import sys
import tarfile
import time
from datetime import datetime, timezone

# Allow importing from parent directory
_parent = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _parent not in sys.path:
    sys.path.insert(0, _parent)

from config import (
    DB_FILE, PORTAL_DB_FILE, AUDIT_DB_FILE,
    DATA_DIR, UPLOAD_FOLDER, PORTAL_UPLOAD_FOLDER,
    KEY_FILE, INSTANCE_DIR, VERSION,
)


def _sha256_file(path):
    """Return hex SHA256 of a file."""
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        while True:
            chunk = f.read(1 << 20)  # 1 MiB
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _sha256_bytes(data):
    """Return hex SHA256 of bytes."""
    return hashlib.sha256(data).hexdigest()


def _db_row_counts(path):
    """Return {table_name: row_count} for a SQLite database."""
    counts = {}
    try:
        conn = sqlite3.connect(path, timeout=10)
        c = conn.cursor()
        tables = [r[0] for r in c.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
        ).fetchall()]
        for t in tables:
            try:
                counts[t] = c.execute(f"SELECT COUNT(*) FROM [{t}]").fetchone()[0]
            except Exception:
                counts[t] = None
        # Integrity check
        ic = c.execute("PRAGMA integrity_check").fetchone()[0]
        counts['__integrity_check'] = ic
        conn.close()
    except Exception as e:
        counts['__error'] = str(e)
    return counts


def _build_restore_md():
    """Return RESTORE.md content as string."""
    return """# AspidusCRM — Restore Instructions

This archive contains a complete backup of your AspidusCRM instance.

## Steps to Restore

1. **Stop the application** (gunicorn / Flask server).

2. **Restore databases:**
   ```bash
   cp databases/aspidus_crm.db    $DATA_DIR/aspidus_crm.db
   cp databases/aspidus_portal.db $DATA_DIR/aspidus_portal.db
   cp databases/aspidus_audit.db  $DATA_DIR/aspidus_audit.db
   ```

3. **Restore encryption keys** (required to decrypt stored passwords, KYC, etc.):
   ```bash
   cp keys/vault.key            $DATA_DIR/vault.key
   cp keys/instance/secret.key  $DATA_DIR/instance/secret.key
   chmod 600 $DATA_DIR/vault.key $DATA_DIR/instance/secret.key
   ```

4. **Restore uploads:**
   ```bash
   cp -r uploads/          $DATA_DIR/uploads/
   cp -r portal_uploads/   $DATA_DIR/portal_uploads/
   ```

5. **Set environment variables** (same values as original instance):
   - `SECRET_KEY` — from the original instance
   - `ENCRYPTION_KEY` — from the original instance
   - `DATA_DIR` — target directory for restored data
   - `ADMIN_PASSWORD` — initial admin password (if fresh DB)

6. **Restart the application.**

7. **Verify** by logging in and checking data integrity.

## Important Notes

- **Keys are critical**: Without the original `vault.key` and `secret.key`, encrypted
  data (SMTP passwords, API keys, KYC documents) cannot be decrypted.
- **Do not mix** backups from different instances — database schema versions must match.
- **Check meta.json** for row counts and SHA256 hashes to verify backup integrity.
- **Backup was created** by AspidusCRM v{version} on {timestamp}.

Generated by db_export_full.py — AspidusCRM v{version}
""".format(version=VERSION, timestamp=datetime.now(timezone.utc).isoformat())


def build_backup(out_path=None, out_stream=None, quiet=False):
    """Build a complete .tar.gz backup.

    Args:
        out_path:    If set, write archive to this file path.
        out_stream:  If set, write archive to this BytesIO stream.
        quiet:       If True, suppress progress output.

    One of out_path or out_stream must be provided.
    """
    if out_path:
        out_stream = open(out_path, 'wb')
        should_close = True
    elif out_stream:
        should_close = False
    else:
        raise ValueError("Either out_path or out_stream must be provided")

    meta = {
        'backup_format_version': '1',
        'app_version': VERSION,
        'version': VERSION,
        'created_utc': datetime.now(timezone.utc).isoformat(),
        'created_at': datetime.now(timezone.utc).isoformat(),
        'databases': {},
        'keys': {},
        'uploads': {'file_count': 0, 'total_bytes': 0},
        'portal_uploads': {'file_count': 0, 'total_bytes': 0},
    }

    try:
        with tarfile.open(fileobj=out_stream, mode='w:gz') as tar:
            # ── 1. DATABASES ──
            db_files = {
                'aspidus_crm.db': DB_FILE,
                'aspidus_portal.db': PORTAL_DB_FILE,
                'aspidus_audit.db': AUDIT_DB_FILE,
            }
            for name, path in db_files.items():
                if not os.path.exists(path):
                    if not quiet:
                        print(f'  [SKIP] {name} — file not found')
                    continue
                arcname = f'databases/{name}'
                tar.add(path, arcname=arcname)
                sha = _sha256_file(path)
                size = os.path.getsize(path)
                counts = _db_row_counts(path)
                meta['databases'][name] = {
                    'sha256': sha,
                    'size_bytes': size,
                    'tables': counts,
                    'integrity_check': counts.pop('__integrity_check', 'unknown'),
                }
                if counts.get('__error'):
                    meta['databases'][name]['error'] = counts.pop('__error')
                if not quiet:
                    print(f'  [OK] {name} — {size/1024:.1f} KB, SHA256={sha[:16]}…')

            # ── 2. KEYS ──
            key_files = {
                'vault.key': KEY_FILE,
                'instance/secret.key': os.path.join(INSTANCE_DIR, 'secret.key'),
            }
            for name, path in key_files.items():
                if not os.path.exists(path):
                    if not quiet:
                        print(f'  [SKIP] keys/{name} — file not found')
                    continue
                arcname = f'keys/{name}'
                tar.add(path, arcname=arcname)
                meta['keys'][name] = {
                    'sha256': _sha256_file(path),
                    'size_bytes': os.path.getsize(path),
                }
                if not quiet:
                    print(f'  [OK] keys/{name}')

            # ── 3. UPLOADS ──
            for folder, label in [
                (UPLOAD_FOLDER, 'uploads'),
                (PORTAL_UPLOAD_FOLDER, 'portal_uploads'),
            ]:
                if not os.path.isdir(folder):
                    if not quiet:
                        print(f'  [SKIP] {label}/ — directory not found')
                    continue
                file_count = 0
                total_bytes = 0
                for root, dirs, files in os.walk(folder):
                    for fname in files:
                        fpath = os.path.join(root, fname)
                        rel = os.path.relpath(fpath, os.path.dirname(folder))
                        tar.add(fpath, arcname=rel)
                        file_count += 1
                        try:
                            total_bytes += os.path.getsize(fpath)
                        except Exception:
                            pass
                meta[label] = {
                    'file_count': file_count,
                    'total_bytes': total_bytes,
                    'total_mb': round(total_bytes / 1024 / 1024, 2),
                }
                if not quiet:
                    print(f'  [OK] {label}/ — {file_count} files, {total_bytes/1024:.1f} KB')

            # ── 4. meta.json ──
            meta_bytes = json.dumps(meta, indent=2, ensure_ascii=False).encode('utf-8')
            info = tarfile.TarInfo(name='meta.json')
            info.size = len(meta_bytes)
            info.mtime = time.time()
            tar.addfile(info, io.BytesIO(meta_bytes))
            if not quiet:
                print(f'  [OK] meta.json — {len(meta_bytes)} bytes')

            # ── 5. RESTORE.md ──
            restore_md = _build_restore_md().encode('utf-8')
            info = tarfile.TarInfo(name='RESTORE.md')
            info.size = len(restore_md)
            info.mtime = time.time()
            tar.addfile(info, io.BytesIO(restore_md))
            if not quiet:
                print(f'  [OK] RESTORE.md — {len(restore_md)} bytes')

    finally:
        if should_close:
            out_stream.close()

    if not quiet:
        print('  [DONE] Backup build complete.')


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='AspidusCRM Full Backup Builder')
    parser.add_argument('-o', '--output', default=None, help='Output .tar.gz file path')
    parser.add_argument('-q', '--quiet', action='store_true', help='Suppress progress output')
    args = parser.parse_args()

    if args.output:
        build_backup(out_path=args.output, quiet=args.quiet)
    else:
        ts = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')
        default = os.path.join(DATA_DIR, f'aspidus_full_backup_{ts}.tar.gz')
        build_backup(out_path=default, quiet=args.quiet)
        print(f'Backup saved to: {default}')
